services:
  kizola:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: kizola
    volumes:
      - .:/home/node/kizola
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - postgres_kizola
    networks:
      - kizola-network

  postgres_kizola:
    image: postgres
    restart: always
    container_name: postgres_kizola
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_kizola:5432/${POSTGRES_DB}?schema=public
    ports:
      - '5432:5432'
    volumes:
      - .:/home/node/postgres/data
    networks:
      - kizola-network

# volumes:
#   kizola:

networks:
  kizola-network:
    driver: bridge
